paises_ciudades = {
    "Afganistán": ["Kabul", "Herat", "Mazar-i-Sharif"],
    "Albania": ["Tirana", "Durrës", "Vlorë"],
    "Alemania": ["Berlín", "Múnich", "Frankfurt"],
    "Andorra": ["Andorra la Vieja", "Escaldes-Engordany", "Encamp"],
    "Angola": ["Luanda", "Huambo", "Lubango"],
    "Antigua y Barbuda": ["Saint John's", "English Harbour", "Bolans"],
    "Arabia Saudita": ["Riad", "Jeddah", "Medina"],
    "Argelia": ["Argel", "Orán", "Constantina"],
    "Argentina": ["Buenos Aires", "Córdoba", "Rosario"],
    "Armenia": ["Ereván", "Gyumri", "Vanadzor"],
    "Australia": ["Sídney", "Melbourne", "Brisbane"],
    "Austria": ["Viena", "Graz", "Linz"],
    "Azerbaiyán": ["Bakú", "Ganja", "Sumgait"],
    "Bahamas": ["Nassau", "Freeport", "Lucaya"],
    "Bangladés": ["Daca", "Chittagong", "Khulna"],
    "Barbados": ["Bridgetown", "Speightstown", "Oistins"],
    "Baréin": ["Manama", "Muharraq", "Riffa"],
    "Bélgica": ["Bruselas", "Amberes", "Gante"],
    "Belice": ["Belmopán", "Belize City", "San Ignacio"],
    "Benín": ["Porto-Novo", "Cotonú", "Parakou"],
    "Bielorrusia": ["Minsk", "Gomel", "Mogilev"],
    "Birmania": ["Naypyidaw", "Yangón", "Mandalay"],
    "Bolivia": ["La Paz", "Santa Cruz de la Sierra", "Cochabamba"],
    "Bosnia y Herzegovina": ["Sarajevo", "Banja Luka", "Zenica"],
    "Botsuana": ["Gaborone", "Francistown", "Serowe"],
    "Brasil": ["São Paulo", "Río de Janeiro", "Brasilia"],
    "Brunéi": ["Bandar Seri Begawan", "Seria", "Kuala Belait"],
    "Bulgaria": ["Sofía", "Plovdiv", "Varna"],
    "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"],
    "Burundi": ["Gitega", "Bujumbura", "Rumonge"],
    "Bután": ["Thimphu", "Phuntsholing", "Punakha"],
    "Cabo Verde": ["Praia", "Mindelo", "Sal"],
    "Camboya": ["Phnom Penh", "Siem Reap", "Sihanoukville"],
    "Camerún": ["Yaundé", "Douala", "Garoua"],
    "Canadá": ["Ottawa", "Toronto", "Vancouver"],
    "Catar": ["Doha", "Al Wakrah", "Al Khor"],
    "Chad": ["N'Djamena", "Moundou", "Sarh"],
    "Chile": ["Santiago", "Valparaíso", "Concepción"],
    "China": ["Pekín", "Shanghái", "Cantón"],
    "Chipre": ["Nicosia", "Limasol", "Larnaca"],
    "Colombia": ["Bogotá", "Medellín", "Cali"],
    "Comoras": ["Moroni", "Moutsamoudou", "Fomboni"],
    "Corea del Norte": ["Pyongyang", "Hamhung", "Nampo"],
    "Corea del Sur": ["Seúl", "Busan", "Incheon"],
    "Costa de Marfil": ["Yamusukro", "Abiyán", "San-Pedro"],
    "Costa Rica": ["San José", "Cartago", "Limón"],
    "Croacia": ["Zagreb", "Split", "Rijeka"],
    "Cuba": ["La Habana", "Santa Clara", "Camagüey"],
    "Dinamarca": ["Copenhague", "Aarhus", "Odense"],
    "Dominica": ["Roseau", "Portsmouth", "Marigot"],
    "Ecuador": ["Quito", "Guayaquil", "Cuenca"],
    "Egipto": ["El Cairo", "Alexandría", "Giza"],
    "El Salvador": ["San Salvador", "Santa Ana", "Santa Tecla"],
    "Emiratos Árabes Unidos": ["Abu Dhabi", "Dubái", "Sharjah"],
    "Eritrea": ["Asmara", "Assab", "Keren"],
    "Eslovaquia": ["Bratislava", "Košice", "Prešov"],
    "Eslovenia": ["Liubliana", "Maribor", "Celje"],
    "España": ["Madrid", "Barcelona", "Valencia"],
    "Estados Unidos": ["Washington D.C.", "Nueva York", "Los Ángeles"],
    "Estonia": ["Tallin", "Tartu", "Narva"],
    "Etiopía": ["Addis Abeba", "Dire Dawa", "Mek'ele"],
    "Filipinas": ["Manila", "Quezon City", "Davao City"],
    "Finlandia": ["Helsinki", "Espoo", "Tampere"],
    "Fiyi": ["Suva", "Lautoka", "Nadi"],
    "Francia": ["París", "Marsella", "Lyon"],
    "Gabón": ["Libreville", "Port-Gentil", "Franceville"],
    "Gambia": ["Banjul", "Serekunda", "Brikama"],
    "Georgia": ["Tiflis", "Batumi", "Kutaisi"],
    "Ghana": ["Acra", "Kumasi", "Tamale"],
    "Granada": ["Saint George's", "Gouyave", "Bridgetown"],
    "Grecia": ["Atenas", "Salónica", "Patras"],
    "Guatemala": ["Ciudad de Guatemala", "Mixco", "Villa Nueva"],
    "Guinea": ["Conakry", "Nzérékoré", "Kankan"],
    "Guinea-Bisáu": ["Bissau", "Bafatá", "Gabú"],
    "Guinea Ecuatorial": ["Malabo", "Bata", "Ebebiyin"],
    "Guyana": ["Georgetown", "Linden", "New Amsterdam"],
    "Haití": ["Puerto Príncipe", "Cap-Haïtien", "Santo Domingo"],
    "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma"],
    "Hungría": ["Budapest", "Debrecen", "Szeged"],
    "India": ["Nueva Delhi", "Mumbai", "Bangalore"],
    "Indonesia": ["Yakarta", "Surabaya", "Medan"],
    "Irak": ["Bagdad", "Mosul", "Erbil"],
    "Irán": ["Teherán", "Mashhad", "Isfahán"],
    "Irlanda": ["Dublín", "Cork", "Limerick"],
    "Islandia": ["Reikiavik", "Kópavogur", "Hafnarfjörður"],
    "Islas Marshall": ["Majuro", "Arno", "Wotje"],
    "Islas Salomón": ["Honiara", "Auki", "Gizo"],
    "Israel": ["Jerusalén", "Tel Aviv", "Haifa"],
    "Italia": ["Roma", "Milán", "Nápoles"],
    "Jamaica": ["Kingston", "Portmore", "Spanish Town"],
    "Japón": ["Tokio", "Yokohama", "Osaka"],
    "Jordania": ["Amán", "Zarqa", "Irbid"],
    "Kazajistán": ["Nur-Sultán", "Almaty", "Shymkent"],
    "Kenia": ["Nairobi", "Mombasa", "Kisumu"],
    "Kirguistán": ["Bishkek", "Osh", "Jalal-Abad"],
    "Kiribati": ["Tarawa", "South Tarawa", "Betio"],
    "Kuwait": ["Ciudad de Kuwait", "Al Ahmadi", "Hawally"],
    "Laos": ["Vientián", "Luang Prabang", "Savannakhet"],
    "Lesoto": ["Maseru", "Butha-Buthe", "Mafeteng"],
    "Letonia": ["Riga", "Daugavpils", "Liepāja"],
    "Líbano": ["Beirut", "Tripoli", "Sidón"],
    "Liberia": ["Monrovia", "Gbarnga", "Buchanan"],
    "Libia": ["Trípoli", "Benghazi", "Misurata"],
    "Liechtenstein": ["Vaduz", "Schaan", "Triesen"],
    "Lituania": ["Vilna", "Kaunas", "Klaipėda"],
    "Luxemburgo": ["Luxemburgo", "Esch-sur-Alzette", "Dudelange"],
    "Macedonia del Norte": ["Skopje", "Bitola", "Kumanovo"],
    "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe"],
    "Malasia": ["Kuala Lumpur", "George Town", "Ipoh"],
    "Malaui": ["Lilongwe", "Zomba", "Blantyre"],
    "Maldivas": ["Malé", "Hithadhoo", "Kudahuvadhoo"],
    "Malí": ["Bamako", "Sikasso", "Mopti"],
    "Malta": ["La Valeta", "Birgu", "Sliema"],
    "Marruecos": ["Rabat", "Casablanca", "Marrakech"],
    "Mauricio": ["Port Louis", "Beau Bassin-Rose Hill", "Curepipe"],
    "Mauritania": ["Nuakchot", "Kaédi", "Zouerate"],
    "México": ["Ciudad de México", "Guadalajara", "Monterrey"],
    "Micronesia": ["Palikir", "Woleai", "Kolonia"],
    "Moldavia": ["Chisináu", "Tiráspol", "Bălți"],
    "Mónaco": ["Mónaco", "La Condamine", "Monte Carlo"],
    "Mongolia": ["Ulán Bator", "Erdenet", "Darkhan"],
    "Montenegro": ["Podgorica", "Nikšić", "Pljevlja"],
    "Mozambique": ["Maputo", "Nampula", "Beira"],
    "Namibia": ["Windhoek", "Rundu", "Walvis Bay"],
    "Nauru": ["Yaren", "Anabar", "Anetan"],
    "Nepal": ["Katmandú", "Pokhara", "Lhasa"],
    "Nicaragua": ["Managua", "León", "Chinandega"],
    "Níger": ["Niamey", "Zinder", "Maradi"],
    "Nigeria": ["Abuya", "Lagos", "Ibadan"],
    "Noruega": ["Oslo", "Bergen", "Trondheim"],
    "Nueva Zelanda": ["Wellington", "Auckland", "Christchurch"],
    "Omán": ["Mascate", "Salalah", "Sohar"],
    "Países Bajos": ["Ámsterdam", "Rotterdam", "La Haya"],
    "Pakistán": ["Islamabad", "Lahore", "Karachi"],
    "Palau": ["Ngerulmud", "Koror", "Melekeok"],
    "Panamá": ["Ciudad de Panamá", "San Miguelito", "David"],
    "Papúa Nueva Guinea": ["Port Moresby", "Lae", "Mount Hagen"],
    "Paraguay": ["Asunción", "Ciudad del Este", "San Lorenzo"],
    "Perú": ["Lima", "Arequipa", "Cuzco"],
    "Polonia": ["Varsovia", "Kraków", "Lodz"],
    "Portugal": ["Lisboa", "Oporto", "Coímbra"],
    "Reino Unido": ["Londres", "Birmingham", "Glasgow"],
    "República Centroafricana": ["Bangui", "Bimbo", "Mbaïki"],
    "República Checa": ["Praga", "Brno", "Ostrava"],
    "República Democrática del Congo": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"],
    "República Dominicana": ["Santo Domingo", "Santiago de los Caballeros", "Puerto Plata"],
    "Ruanda": ["Kigali", "Butare", "Gisenyi"],
    "Rumania": ["Bucarest", "Cluj-Napoca", "Timișoara"],
    "Rusia": ["Moscú", "San Petersburgo", "Novosibirsk"],
    "Samoa": ["Apia", "Tuanaimato", "Savai'i"],
    "San Cristóbal y Nieves": ["Basseterre", "Charlestown", "Gingerland"],
    "San Marino": ["San Marino", "Serravalle", "Domagnano"],
    "San Vicente y las Granadinas": ["Kingstown", "Kingstown Park", "Georgetown"],
    "Santa Lucía": ["Castries", "Vieux Fort", "Gros Islet"],
    "Santo Tomé y Príncipe": ["Santo Tomé", "São Tomé", "Trindade"],
    "Senegal": ["Dakar", "Thiès", "Kaolack"],
    "Serbia": ["Belgrado", "Niš", "Novi Sad"],
    "Seychelles": ["Victoria", "Anse Boileau", "Anse Royale"],
    "Sierra Leona": ["Freetown", "Bo", "Makeni"],
    "Singapur": ["Singapur", "Yishun", "Woodlands"],
    "Siria": ["Damasco", "Alepo", "Homs"],
    "Somalia": ["Mogadiscio", "Hargeisa", "Kismayo"],
    "Sri Lanka": ["Colombo", "Kandy", "Galle"],
    "Suazilandia": ["Mbabane", "Manzini", "Piggs Peak"],
    "Sudáfrica": ["Johannesburgo", "Ciudad del Cabo", "Durban"],
    "Sudán": ["Jartum", "Omdurman", "Khartoum North"],
    "Sudán del Sur": ["Yuba", "Wau", "Malakal"],
    "Suecia": ["Estocolmo", "Gotemburgo", "Malmö"],
    "Suiza": ["Zúrich", "Ginebra", "Basilea"],
    "Surinam": ["Paramaribo", "Lelydorp", "Nieuw Nickerie"],
    "Tailandia": ["Bangkok", "Chiang Mai", "Pattaya"],
    "Tanzania": ["Dodoma", "Dar es Salaam", "Mwanza"],
    "Tayikistán": ["Dushanbe", "Khujand", "Kulob"],
    "Timor Oriental": ["Dili", "Baucau", "Suai"],
    "Togo": ["Lomé", "Sokodé", "Kara"],
    "Tonga": ["Nuku'alofa", "Neiafu", "Pangai"],
    "Trinidad y Tobago": ["Puerto España", "San Fernando", "San Juan"],
    "Túnez": ["Túnez", "Sfax", "Sousse"],
    "Turkmenistán": ["Ashgabat", "Türkmenabat", "Daşoguz"],
    "Turquía": ["Ankara", "Estambul", "Izmir"],
    "Tuvalu": ["Funafuti", "Fongafale", "Vaitupu"],
    "Ucrania": ["Kiev", "Járkov", "Odesa"],
    "Uganda": ["Kampala", "Gulu", "Mbarara"],
    "Uruguay": ["Montevideo", "Salto", "Paysandú"],
    "Uzbekistán": ["Tashkent", "Samarkand", "Bukhara"],
    "Vanuatu": ["Port Vila", "Luganville", "Isangel"],
    "Vaticano": ["Ciudad del Vaticano", "Vaticano", "Ciudad Estatal de la Ciudad del Vaticano"],
    "Venezuela": ["Caracas", "Maracaibo", "Valencia"],
    "Vietnam": ["Hanoi", "Ho Chi Minh City", "Da Nang"],
    "Yemen": ["Sana'a", "Aden", "Ta'izz"],
    "Yibuti": ["Yibuti", "Tadjoura", "Arta"],
    "Zambia": ["Lusaka", "Ndola", "Kitwe"],
    "Zimbabue": ["Harare", "Bulawayo", "Mutare"]
    }

nombres = [
    "Ana", "Juan", "María", "Carlos", "Laura", "Pedro", "Sofía", "Luis",
    "Isabel", "Miguel", "Carmen", "José", "Elena", "Antonio", "Patricia",
    "Manuel", "Silvia", "Francisco", "Rosa", "David", "Marta", "Javier",
    "Lucía", "Rafael", "Nuria", "Jesús", "Sara", "Daniel", "Alicia", "Sergio",
    "Andrés", "Paula", "Fernando", "Cristina", "Alberto", "Beatriz", "Roberto",
    "Eva", "Enrique", "Mónica", "Diego", "Raquel", "Óscar", "Sandra", "Víctor",
    "Pilar", "Adrián", "Susana", "Rubén", "Aurora", "Álvaro", "Teresa", "Jorge",
    "Mario", "Clara", "Eduardo", "Irene", "Joaquín", "Julia", "Alfredo", "Natalia",
    "Emilio", "Verónica", "Guillermo", "Esther", "Félix", "Inés", "Héctor", "Lidia",
    "Iván", "Claudia", "Jorge", "Celia", "Ricardo", "Amelia", "Salvador", "Carlota",
    "Federico", "Marina", "Agustín", "Nerea", "Benito", "Yolanda", "César", "Miriam",
    "Leopoldo", "Noelia", "Marcos", "Rebeca", "Gerardo", "Vanesa", "Santiago", "Ainhoa",
    "Ignacio", "Lorena", "Bernardo", "Aitana", "Valentín", "Candela", "Eusebio", "Gema",
    "Ramón", "Laia", "Tomás", "Naiara", "Vicente", "Iria", "Sebastián", "Aroa",
    "Fernando", "Alba", "Gustavo", "Celia", "Rodrigo", "Lara", "Mateo", "Eva"
]

apellidos = [
    "García", "Rodríguez", "González", "Fernández", "López", "Martínez",
    "Sánchez", "Pérez", "Gómez", "Martín", "Jiménez", "Ruiz", "Hernández",
    "Díaz", "Moreno", "Álvarez", "Muñoz", "Romero", "Navarro", "Torres",
    "Domínguez", "Vázquez", "Ramos", "Gil", "Molina", "Ortega", "Delgado",
    "Serrano", "Ramírez", "Lorenzo", "Castro", "Iglesias", "Flores", "Suárez",
    "Cabrera", "Núñez", "Marín", "Blanco", "Márquez", "Vidal", "Santos",
    "Guerrero", "Cortés", "Medina", "Castillo", "Gutiérrez", "Reyes", "Morales",
    "Cruz", "Giménez", "Ortiz", "Gallego", "León", "Herrera", "Marcos", "Soto",
    "Vega", "Lara", "Rubio", "Campos", "Vargas", "Fuentes", "Cano", "Pascual",
    "Santana", "Guerra", "Crespo", "Lozano", "Riera", "Mora", "Naranjo", "Pardo",
    "Rojas", "Caballero", "Montero", "Soler", "Garrido", "Velasco", "Castaño",
    "Prieto", "Carrasco", "Mendoza", "Calvo", "Robles", "Bermúdez", "Pinto",
    "Arias", "Sáez", "Cordero", "Peña", "Aguilar", "Hidalgo", "Otero", "Espinosa",
    "Arroyo", "Vera", "Segura", "Merino", "Montes", "Cuevas", "Bueno", "Rivas",
    "Mateo", "Cabello", "Vicente", "Sierra", "Parra", "Lucas", "Roldán", "Bravo"
]

aerolineas = ["Aerolíneas Argentinas", "Flybondi", "Austral", "Aerolinea-1"]

caracteristicas = ["Interior", "Exterior", "Acuática", "Nocturna", "Familiar"]

paises_aeropuertos = {
    "Afganistán": ["Aeropuerto Internacional de Kabul"],
    "Albania": ["Aeropuerto Internacional de Tirana"],
    "Alemania": ["Aeropuerto de Berlín-Brandeburgo", "Aeropuerto de Múnich", "Aeropuerto de Frankfurt"],
    "Andorra": ["Aeropuerto de Andorra-La Seu d'Urgell"],
    "Angola": ["Aeropuerto Internacional Quatro de Fevereiro"],
    "Antigua y Barbuda": ["Aeropuerto Internacional V. C. Bird"],
    "Arabia Saudita": ["Aeropuerto Internacional Rey Khalid", "Aeropuerto Internacional Rey Abdulaziz", "Aeropuerto Internacional Príncipe Mohammad bin Abdulaziz"],
    "Argelia": ["Aeropuerto Internacional Houari Boumediene"],
    "Argentina": ["Aeropuerto Internacional Ministro Pistarini", "Aeropuerto Internacional Ingeniero Aeronáutico Ambrosio L.V. Taravella", "Aeropuerto Internacional Rosario Islas Malvinas"],
    "Armenia": ["Aeropuerto Internacional de Zvartnots"],
    "Australia": ["Aeropuerto de Sídney", "Aeropuerto de Melbourne", "Aeropuerto de Brisbane"],
    "Austria": ["Aeropuerto de Viena", "Aeropuerto de Graz", "Aeropuerto de Linz"],
    "Azerbaiyán": ["Aeropuerto Internacional Heydar Aliyev"],
    "Bahamas": ["Aeropuerto Internacional Lynden Pindling"],
    "Bangladés": ["Aeropuerto Internacional Hazrat Shahjalal"],
    "Barbados": ["Aeropuerto Internacional Grantley Adams"],
    "Baréin": ["Aeropuerto Internacional de Baréin"],
    "Bélgica": ["Aeropuerto de Bruselas", "Aeropuerto de Amberes", "Aeropuerto de Gante"],
    "Belice": ["Aeropuerto Internacional Philip S. W. Goldson"],
    "Benín": ["Aeropuerto de Cadjehoun"],
    "Bielorrusia": ["Aeropuerto Nacional de Minsk"],
    "Birmania": ["Aeropuerto Internacional de Yangón"],
    "Bolivia": ["Aeropuerto Internacional El Alto", "Aeropuerto Internacional Viru Viru", "Aeropuerto Internacional Jorge Wilstermann"],
    "Bosnia y Herzegovina": ["Aeropuerto Internacional de Sarajevo"],
    "Botsuana": ["Aeropuerto Internacional Sir Seretse Khama"],
    "Brasil": ["Aeropuerto Internacional de São Paulo-Guarulhos", "Aeropuerto Internacional de Río de Janeiro-Galeão", "Aeropuerto Internacional de Brasilia"],
    "Brunéi": ["Aeropuerto Internacional de Brunei"],
    "Bulgaria": ["Aeropuerto de Sofía", "Aeropuerto de Plovdiv", "Aeropuerto de Varna"],
    "Burkina Faso": ["Aeropuerto de Uagadugú"],
    "Burundi": ["Aeropuerto Internacional de Bujumbura"],
    "Bután": ["Aeropuerto Internacional de Paro"],
    "Cabo Verde": ["Aeropuerto Internacional Amílcar Cabral"],
    "Camboya": ["Aeropuerto Internacional de Phnom Penh", "Aeropuerto Internacional de Siem Reap"],
    "Camerún": ["Aeropuerto Internacional de Duala"],
    "Canadá": ["Aeropuerto Internacional de Toronto Pearson", "Aeropuerto Internacional de Vancouver", "Aeropuerto Internacional de Montreal-Trudeau"],
    "Catar": ["Aeropuerto Internacional Hamad"],
    "Chad": ["Aeropuerto Internacional de Yamena"],
    "Chile": ["Aeropuerto Internacional Comodoro Arturo Merino Benítez"],
    "China": ["Aeropuerto Internacional de Pekín-Capital", "Aeropuerto Internacional de Shanghái-Pudong", "Aeropuerto Internacional de Cantón-Baiyun"],
    "Chipre": ["Aeropuerto Internacional de Lárnaca"],
    "Colombia": ["Aeropuerto Internacional El Dorado", "Aeropuerto Internacional José María Córdova", "Aeropuerto Internacional Alfonso Bonilla Aragón"],
    "Comoras": ["Aeropuerto Internacional Príncipe Said Ibrahim"],
    "Corea del Norte": ["Aeropuerto Internacional de Sunan"],
    "Corea del Sur": ["Aeropuerto Internacional de Incheon", "Aeropuerto Internacional de Gimpo", "Aeropuerto Internacional de Gimhae"],
    "Costa de Marfil": ["Aeropuerto Internacional Félix Houphouët-Boigny"],
    "Costa Rica": ["Aeropuerto Internacional Juan Santamaría", "Aeropuerto Internacional Daniel Oduber Quirós"],
    "Croacia": ["Aeropuerto de Zagreb", "Aeropuerto de Split", "Aeropuerto de Rijeka"],
    "Cuba": ["Aeropuerto Internacional José Martí"],
    "Dinamarca": ["Aeropuerto de Copenhague-Kastrup"],
    "Dominica": ["Aeropuerto de Canefield"],
    "Ecuador": ["Aeropuerto Internacional Mariscal Sucre", "Aeropuerto Internacional José Joaquín de Olmedo"],
    "Egipto": ["Aeropuerto Internacional de El Cairo"],
    "El Salvador": ["Aeropuerto Internacional de El Salvador"],
    "Emiratos Árabes Unidos": ["Aeropuerto Internacional de Dubái", "Aeropuerto Internacional de Abu Dhabi", "Aeropuerto Internacional de Sharjah"],
    "Eritrea": ["Aeropuerto Internacional de Asmara"],
    "Eslovaquia": ["Aeropuerto de Bratislava"],
    "Eslovenia": ["Aeropuerto de Liubliana"],
    "España": ["Aeropuerto Adolfo Suárez Madrid-Barajas", "Aeropuerto de Barcelona-El Prat", "Aeropuerto de Valencia"],
    "Estados Unidos": ["Aeropuerto Internacional de Los Ángeles", "Aeropuerto Internacional John F. Kennedy", "Aeropuerto Internacional O'Hare"],
    "Estonia": ["Aeropuerto de Tallin"],
    "Etiopía": ["Aeropuerto Internacional de Bole"],
    "Filipinas": ["Aeropuerto Internacional Ninoy Aquino", "Aeropuerto Internacional de Mactan-Cebú", "Aeropuerto Internacional Francisco Bangoy"],
    "Finlandia": ["Aeropuerto de Helsinki-Vantaa"],
    "Fiyi": ["Aeropuerto Internacional de Nadi"],
    "Francia": ["Aeropuerto de París-Charles de Gaulle", "Aeropuerto de París-Orly", "Aeropuerto de Niza-Costa Azul"],
    "Gabón": ["Aeropuerto Internacional Leon M'ba"],
    "Gambia": ["Aeropuerto Internacional de Banjul"],
    "Georgia": ["Aeropuerto Internacional de Tiflis"],
    "Ghana": ["Aeropuerto Internacional de Kotoka"],
    "Granada": ["Aeropuerto Internacional Maurice Bishop"],
    "Grecia": ["Aeropuerto Internacional Eleftherios Venizelos"],
    "Guatemala": ["Aeropuerto Internacional La Aurora"],
    "Guinea": ["Aeropuerto Internacional de Conakry"],
    "Guinea-Bisáu": ["Aeropuerto Internacional Osvaldo Vieira"],
    "Guinea Ecuatorial": ["Aeropuerto de Malabo"],
    "Guyana": ["Aeropuerto Internacional Cheddi Jagan"],
    "Haití": ["Aeropuerto Internacional Toussaint Louverture"],
    "Honduras": ["Aeropuerto Internacional Ramón Villeda Morales"],
    "Hungría": ["Aeropuerto de Budapest-Ferenc Liszt"],
    "India": ["Aeropuerto Internacional Indira Gandhi", "Aeropuerto Internacional Chhatrapati Shivaji", "Aeropuerto Internacional de Bangalore"],
    "Indonesia": ["Aeropuerto Internacional Soekarno-Hatta", "Aeropuerto Internacional Juanda", "Aeropuerto Internacional Ngurah Rai"],
    "Irak": ["Aeropuerto Internacional de Bagdad"],
    "Irán": ["Aeropuerto Internacional Imán Jomeini"],
    "Irlanda": ["Aeropuerto de Dublín"],
    "Islandia": ["Aeropuerto Internacional de Keflavík"],
    "Islas Marshall": ["Aeropuerto Internacional Amata Kabua"],
    "Islas Salomón": ["Aeropuerto Internacional de Honiara"],
    "Israel": ["Aeropuerto Internacional Ben Gurión"],
    "Italia": ["Aeropuerto de Roma-Fiumicino", "Aeropuerto de Milán-Malpensa", "Aeropuerto de Venecia-Marco Polo"],
    "Jamaica": ["Aeropuerto Internacional Norman Manley"],
    "Japón": ["Aeropuerto Internacional de Narita", "Aeropuerto Internacional de Kansai", "Aeropuerto Internacional de Haneda"],
    "Jordania": ["Aeropuerto Internacional Reina Alia"],
    "Kazajistán": ["Aeropuerto Internacional de Nursultán Nazarbáyev"],
    "Kenia": ["Aeropuerto Internacional Jomo Kenyatta"],
    "Kirguistán": ["Aeropuerto Internacional de Manas"],
    "Kiribati": ["Aeropuerto Internacional de Bonriki"],
    "Kuwait": ["Aeropuerto Internacional de Kuwait"],
    "Laos": ["Aeropuerto Internacional de Wattay"],
    "Lesoto": ["Aeropuerto Internacional Moshoeshoe I"],
    "Letonia": ["Aeropuerto Internacional de Riga"],
    "Líbano": ["Aeropuerto Internacional Rafic Hariri"],
    "Liberia": ["Aeropuerto Internacional Roberts"],
    "Libia": ["Aeropuerto Internacional de Trípoli"],
    "Liechtenstein": ["Aeropuerto de Zúrich"],
    "Lituania": ["Aeropuerto de Vilna"],
    "Luxemburgo": ["Aeropuerto de Luxemburgo"],
    "Macedonia del Norte": ["Aeropuerto de Skopie"],
    "Madagascar": ["Aeropuerto Internacional Ivato"],
    "Malasia": ["Aeropuerto Internacional de Kuala Lumpur"],
    "Malaui": ["Aeropuerto Internacional Kamuzu"],
    "Maldivas": ["Aeropuerto Internacional de Malé"],
    "Malí": ["Aeropuerto Internacional de Bamako-Sénou"],
    "Malta": ["Aeropuerto Internacional de Malta"],
    "Marruecos": ["Aeropuerto Internacional Mohammed V"],
    "Mauricio": ["Aeropuerto Internacional Sir Seewoosagur Ramgoolam"],
    "Mauritania": ["Aeropuerto Internacional de Nuakchot-Oumtounsy"],
    "México": ["Aeropuerto Internacional de la Ciudad de México", "Aeropuerto Internacional de Guadalajara", "Aeropuerto Internacional de Cancún"],
    "Micronesia": ["Aeropuerto Internacional de Pohnpei"],
    "Moldavia": ["Aeropuerto Internacional de Chisináu"],
    "Mónaco": ["Aeropuerto de Niza-Costa Azul"],
    "Mongolia": ["Aeropuerto Internacional Gengis Kan"],
    "Montenegro": ["Aeropuerto de Podgorica"],
    "Mozambique": ["Aeropuerto Internacional de Maputo"],
    "Namibia": ["Aeropuerto Internacional Hosea Kutako"],
    "Nauru": ["Aeropuerto Internacional de Nauru"],
    "Nepal": ["Aeropuerto Internacional de Tribhuvan"],
    "Nicaragua": ["Aeropuerto Internacional Augusto C. Sandino"],
    "Níger": ["Aeropuerto Internacional Diori Hamani"],
    "Nigeria": ["Aeropuerto Internacional Murtala Muhammed"],
    "Noruega": ["Aeropuerto de Oslo-Gardermoen"],
    "Nueva Zelanda": ["Aeropuerto de Auckland", "Aeropuerto de Christchurch", "Aeropuerto de Wellington"],
    "Omán": ["Aeropuerto Internacional de Mascate"],
    "Países Bajos": ["Aeropuerto de Ámsterdam-Schiphol"],
    "Pakistán": ["Aeropuerto Internacional Jinnah"],
    "Palau": ["Aeropuerto Internacional Roman Tmetuchl"],
    "Panamá": ["Aeropuerto Internacional de Tocumen"],
    "Papúa Nueva Guinea": ["Aeropuerto Internacional Jacksons"],
    "Paraguay": ["Aeropuerto Internacional Silvio Pettirossi"],
    "Perú": ["Aeropuerto Internacional Jorge Chávez"],
    "Polonia": ["Aeropuerto de Varsovia-Chopin"],
    "Portugal": ["Aeropuerto de Lisboa", "Aeropuerto de Oporto", "Aeropuerto de Faro"],
    "Reino Unido": ["Aeropuerto de Londres-Heathrow", "Aeropuerto de Londres-Gatwick", "Aeropuerto de Mánchester"],
    "República Centroafricana": ["Aeropuerto Internacional Bangui M'Poko"],
    "República Checa": ["Aeropuerto de Praga-Václav Havel"],
    "República Democrática del Congo": ["Aeropuerto Internacional de N'djili"],
    "República Dominicana": ["Aeropuerto Internacional de Las Américas"],
    "Ruanda": ["Aeropuerto Internacional de Kigali"],
    "Rumania": ["Aeropuerto Internacional Henri Coandă"],
    "Rusia": ["Aeropuerto Internacional de Moscú-Sheremétievo", "Aeropuerto Internacional de Moscú-Domodédovo", "Aeropuerto Internacional de San Petersburgo-Púlkovo"],
    "Samoa": ["Aeropuerto Internacional Faleolo"],
    "San Cristóbal y Nieves": ["Aeropuerto Internacional Robert L. Bradshaw"],
    "San Marino": ["Aeropuerto Internacional Federico Fellini"],
    "San Vicente y las Granadinas": ["Aeropuerto Internacional Argyle"],
    "Santa Lucía": ["Aeropuerto Internacional Hewanorra"],
    "Santo Tomé y Príncipe": ["Aeropuerto Internacional de São Tomé"],
    "Senegal": ["Aeropuerto Internacional Blaise Diagne"],
    "Serbia": ["Aeropuerto de Belgrado-Nikola Tesla"],
    "Seychelles": ["Aeropuerto Internacional de Seychelles"],
    "Sierra Leona": ["Aeropuerto Internacional de Lungi"],
    "Singapur": ["Aeropuerto de Singapur-Changi"],
    "Siria": ["Aeropuerto Internacional de Damasco"],
    "Somalia": ["Aeropuerto Internacional Aden Adde"],
    "Sri Lanka": ["Aeropuerto Internacional Bandaranaike"],
    "Suazilandia": ["Aeropuerto Internacional Rey Mswati III"],
    "Sudáfrica": ["Aeropuerto Internacional O.R. Tambo", "Aeropuerto Internacional de Ciudad del Cabo", "Aeropuerto Internacional Rey Shaka"],
    "Sudán": ["Aeropuerto Internacional de Jartum"],
    "Sudán del Sur": ["Aeropuerto Internacional de Yuba"],
    "Suecia": ["Aeropuerto de Estocolmo-Arlanda"],
    "Suiza": ["Aeropuerto de Zúrich", "Aeropuerto de Ginebra", "Aeropuerto de Basilea-Mulhouse-Friburgo"],
    "Surinam": ["Aeropuerto Internacional Johan Adolf Pengel"],
    "Tailandia": ["Aeropuerto Internacional Suvarnabhumi", "Aeropuerto Internacional Don Mueang", "Aeropuerto Internacional de Phuket"],
    "Tanzania": ["Aeropuerto Internacional Julius Nyerere"],
    "Tayikistán": ["Aeropuerto Internacional de Dushanbe"],
    "Timor Oriental": ["Aeropuerto Internacional Presidente Nicolau Lobato"],
    "Togo": ["Aeropuerto Internacional de Lomé-Tokoin"],
    "Tonga": ["Aeropuerto Internacional Fua'amotu"],
    "Trinidad y Tobago": ["Aeropuerto Internacional de Piarco"],
    "Túnez": ["Aeropuerto Internacional de Túnez-Cartago"],
    "Turkmenistán": ["Aeropuerto Internacional de Ashgabat"],
    "Turquía": ["Aeropuerto de Estambul", "Aeropuerto Internacional Sabiha Gökçen", "Aeropuerto de Antalya"],
    "Tuvalu": ["Aeropuerto Internacional de Funafuti"],
    "Ucrania": ["Aeropuerto Internacional de Boryspil"],
    "Uganda": ["Aeropuerto Internacional de Entebbe"],
    "Uruguay": ["Aeropuerto Internacional de Carrasco"],
    "Uzbekistán": ["Aeropuerto Internacional de Tashkent"],
    "Vanuatu": ["Aeropuerto Internacional Bauerfield"],
    "Vaticano": ["Helipuerto de la Ciudad del Vaticano"],
    "Venezuela": ["Aeropuerto Internacional de Maiquetía Simón Bolívar"],
    "Vietnam": ["Aeropuerto Internacional de Noi Bai", "Aeropuerto Internacional de Tan Son Nhat", "Aeropuerto Internacional de Da Nang"],
    "Yemen": ["Aeropuerto Internacional de Sana'a"],
    "Yibuti": ["Aeropuerto Internacional de Yibuti-Ambouli"],
    "Zambia": ["Aeropuerto Internacional Kenneth Kaunda"],
    "Zimbabue": ["Aeropuerto Internacional Robert Gabriel Mugabe"]
}

paises_atracciones = {
    "Afganistán": ["Mezquita Azul de Mazar-i-Sharif", "Jardines de Babur", "Fortaleza de Bala Hissar"],
    "Albania": ["Castillo de Rozafa", "Plaza Skanderbeg", "Anfiteatro de Durrës"],
    "Alemania": ["Puerta de Brandeburgo", "Catedral de Colonia", "Castillo de Neuschwanstein"],
    "Andorra": ["Naturlandia", "Caldea", "Vallnord"],
    "Angola": ["Fortaleza de São Miguel", "Parque Nacional de Kissama", "Museo Nacional de Antropología"],
    "Antigua y Barbuda": ["Nelson's Dockyard", "Shirley Heights", "Devil's Bridge"],
    "Arabia Saudita": ["Masjid al-Haram", "Al-Masjid an-Nabawi", "Mada'in Saleh"],
    "Argelia": ["Casba de Argel", "Ruinas de Timgad", "M'Zab Valley"],
    "Argentina": ["Cataratas del Iguazú", "Glaciar Perito Moreno", "Parque Nacional Los Glaciares"],
    "Armenia": ["Monasterio de Khor Virap", "Catedral de Echmiadzin", "Monasterio de Geghard"],
    "Australia": ["Ópera de Sídney", "Gran Barrera de Coral", "Uluru"],
    "Austria": ["Palacio de Schönbrunn", "Catedral de San Esteban", "Palacio de Hofburg"],
    "Azerbaiyán": ["Ciudad Vieja de Bakú", "Palacio de los Shirvanshahs", "Torre de la Doncella"],
    "Bahamas": ["Atlantis Paradise Island", "Playa de Pink Sands", "Parque Nacional Lucayan"],
    "Bangladés": ["Mezquita Baitul Mukarram", "Fuerte de Lalbagh", "Parque Nacional de Sundarbans"],
    "Barbados": ["Playa de Crane", "Cueva de Harrison", "Jardines de Andrómeda"],
    "Baréin": ["Fuerte de Baréin", "Mezquita Al-Fateh", "Museo Nacional de Baréin"],
    "Bélgica": ["Atomium", "Grand Place", "Manneken Pis"],
    "Belice": ["Gran Agujero Azul", "Ruinas de Xunantunich", "Cayo Ambergris"],
    "Benín": ["Palacio Real de Abomey", "Templo de los Pitones", "Parque Nacional de Pendjari"],
    "Bielorrusia": ["Castillo de Mir", "Castillo de Nesvizh", "Parque Nacional de Belovezhskaya Pushcha"],
    "Birmania": ["Pagoda Shwedagon", "Bagan", "Lago Inle"],
    "Bolivia": ["Salar de Uyuni", "Lago Titicaca", "Parque Nacional Madidi"],
    "Bosnia y Herzegovina": ["Puente Stari Most", "Baščaršija", "Fuerte de Blagaj"],
    "Botsuana": ["Delta del Okavango", "Parque Nacional Chobe", "Reserva de Caza del Kalahari Central"],
    "Brasil": ["Cristo Redentor", "Cataratas del Iguazú", "Playa de Copacabana"],
    "Brunéi": ["Mezquita Omar Ali Saifuddien", "Palacio Nurul Iman", "Parque Nacional Ulu Temburong"],
    "Bulgaria": ["Monasterio de Rila", "Catedral de Alejandro Nevski", "Playa del Sol"],
    "Burkina Faso": ["Parque Nacional de Arli", "Mezquita de Bobo-Dioulasso", "Ruinas de Loropéni"],
    "Burundi": ["Parque Nacional de Kibira", "Lago Tanganica", "Cascadas de Kagera"],
    "Bután": ["Monasterio de Taktsang", "Fuerte de Punakha", "Monasterio de Tashichho Dzong"],
    "Cabo Verde": ["Playa de Santa María", "Volcán Pico do Fogo", "Valle de Paul"],
    "Camboya": ["Angkor Wat", "Angkor Thom", "Tonlé Sap"],
    "Camerún": ["Parque Nacional de Waza", "Montañas Mandara", "Cascadas de Lobé"],
    "Canadá": ["Cataratas del Niágara", "Parque Nacional Banff", "Torre CN"],
    "Catar": ["Museo de Arte Islámico", "La Perla", "Souq Waqif"],
    "Chad": ["Lago Chad", "Desierto de Ennedi", "Parque Nacional de Zakouma"],
    "Chile": ["Torres del Paine", "Desierto de Atacama", "Isla de Pascua"],
    "China": ["Gran Muralla China", "Ciudad Prohibida", "Ejército de Terracota"],
    "Chipre": ["Tumbas de los Reyes", "Castillo de Kolossi", "Monasterio de Kykkos"],
    "Colombia": ["Ciudad Perdida", "Parque Nacional Natural Tayrona", "Catedral de Sal de Zipaquirá"],
    "Comoras": ["Parque Nacional de Coelacanth", "Monte Karthala", "Playa de Itsandra"],
    "Corea del Norte": ["Monte Paektu", "Mausoleo de Kumsusan", "Arco del Triunfo"],
    "Corea del Sur": ["Palacio de Gyeongbokgung", "Mercado de Namdaemun", "Parque Nacional de Seoraksan"],
    "Costa de Marfil": ["Basílica de Nuestra Señora de la Paz", "Parque Nacional de Taï", "Gran Mezquita de Kong"],
    "Costa Rica": ["Parque Nacional Manuel Antonio", "Volcán Arenal", "Parque Nacional Tortuguero"],
    "Croacia": ["Murallas de Dubrovnik", "Parque Nacional de los Lagos de Plitvice", "Palacio de Diocleciano"],
    "Cuba": ["El Malecón", "Plaza de la Revolución", "Varadero"],
    "Dinamarca": ["La Sirenita", "Tivoli Gardens", "Castillo de Kronborg"],
    "Dominica": ["Boiling Lake", "Parque Nacional de Morne Trois Pitons", "Emerald Pool"],
    "Ecuador": ["Islas Galápagos", "Cotopaxi", "Quito"],
    "Egipto": ["Pirámides de Giza", "Templo de Karnak", "Valle de los Reyes"],
    "El Salvador": ["Parque Nacional El Boquerón", "Ruinas de Joya de Cerén", "Volcán de Izalco"],
    "Emiratos Árabes Unidos": ["Burj Khalifa", "Mezquita Sheikh Zayed", "Palm Jumeirah"],
    "Eritrea": ["Asmara", "Massawa", "Dahlak Archipelago"],
    "Eslovaquia": ["Castillo de Bratislava", "Castillo de Spiš", "Parque Nacional de Tatra"],
    "Eslovenia": ["Lago Bled", "Cuevas de Postojna", "Castillo de Predjama"],
    "España": ["La Alhambra", "Sagrada Familia", "Museo del Prado"],
    "Estados Unidos": ["Estado de la Libertad", "Gran Cañón", "Parque Nacional de Yellowstone"],
    "Estonia": ["Ciudad Vieja de Tallin", "Castillo de Toompea", "Parque Nacional de Lahemaa"],
    "Etiopía": ["Iglesias de Lalibela", "Parque Nacional de Simien", "Castillo de Fasil Ghebbi"],
    "Filipinas": ["Isla de Boracay", "Río Subterráneo de Puerto Princesa", "Terrazas de Arroz de Banaue"],
    "Finlandia": ["Aurora Boreal", "Fortaleza de Suomenlinna", "Parque Nacional de Nuuksio"],
    "Fiyi": ["Islas Mamanuca", "Islas Yasawa", "Parque Nacional de Bouma"],
    "Francia": ["Torre Eiffel", "Palacio de Versalles", "Mont Saint-Michel"],
    "Gabón": ["Parque Nacional de Loango", "Parque Nacional de Lopé", "Cascadas de Kongou"],
    "Gambia": ["Parque Nacional de Kiang West", "Mercado de Albert", "Fuerte James Island"],
    "Georgia": ["Catedral de Svetitskhoveli", "Monasterio de Gelati", "Cuevas de Vardzia"],
    "Ghana": ["Fuerte de Elmina", "Parque Nacional de Mole", "Mercado de Makola"],
    "Granada": ["Grand Anse Beach", "Fort George", "Playa de Morne Rouge"],
    "Grecia": ["Acrópolis de Atenas", "Santorini", "Meteora"],
    "Guatemala": ["Tikal", "Lago de Atitlán", "Antigua Guatemala"],
    "Guinea": ["Cascadas de Kambadaga", "Parque Nacional de Monte Nimba", "Islas de Los"],
    "Guinea-Bisáu": ["Parque Nacional de Orango", "Islas Bijagós", "Fuerte de Cacheu"],
    "Guinea Ecuatorial": ["Isla de Bioko", "Parque Nacional de Monte Alén", "Cascadas de Iladyi"],
    "Guyana": ["Cascadas de Kaieteur", "Parque Nacional de Iwokrama", "Mercado de Stabroek"],
    "Haití": ["Citadelle Laferrière", "Palacio de Sans-Souci", "Playa de Labadee"],
    "Honduras": ["Ruinas de Copán", "Parque Nacional de Pico Bonito", "Islas de la Bahía"],
    "Hungría": ["Parlamento de Budapest", "Baños Széchenyi", "Castillo de Buda"],
    "India": ["Taj Mahal", "Fuerte Rojo", "Templo Dorado"],
    "Indonesia": ["Borobudur", "Bali", "Parque Nacional de Komodo"],
    "Irak": ["Ciudadela de Erbil", "Zigurat de Ur", "Mezquita de Al-Askari"],
    "Irán": ["Persépolis", "Plaza de Naqsh-e Jahan", "Mezquita del Imán"],
    "Irlanda": ["Acantilados de Moher", "Castillo de Blarney", "Guinness Storehouse"],
    "Islandia": ["Laguna Azul", "Geiser de Geysir", "Cascadas de Gullfoss"],
    "Islas Marshall": ["Atolón de Bikini", "Isla de Majuro", "Isla de Ebeye"],
    "Islas Salomón": ["Isla de Guadalcanal", "Isla de Malaita", "Isla de Santa Isabel"],
    "Israel": ["Muro de los Lamentos", "Mar Muerto", "Masada"],
    "Italia": ["Coliseo", "Canales de Venecia", "Torre de Pisa"],
    "Jamaica": ["Dunn's River Falls", "Blue Mountains", "Negril"],
    "Japón": ["Monte Fuji", "Templo de Kinkaku-ji", "Santuario de Fushimi Inari"],
    "Jordania": ["Petra", "Mar Muerto", "Wadi Rum"],
    "Kazajistán": ["Lago Balkhash", "Parque Nacional de Altyn-Emel", "Mausoleo de Khoja Ahmed Yasawi"],
    "Kenia": ["Parque Nacional de Masai Mara", "Parque Nacional de Amboseli", "Parque Nacional de Tsavo"],
    "Kirguistán": ["Lago Issyk-Kul", "Parque Nacional de Ala Archa", "Tash Rabat"],
    "Kiribati": ["Atolón de Tarawa", "Isla de Kiritimati", "Isla de Tabuaeran"],
    "Kuwait": ["Torres de Kuwait", "Gran Mezquita de Kuwait", "Museo Nacional de Kuwait"],
    "Laos": ["Luang Prabang", "Playa de las Jarras", "Cascadas de Kuang Si"],
    "Lesoto": ["Parque Nacional de Sehlabathebe", "Cascadas de Maletsunyane", "Paso de Sani"],
    "Letonia": ["Ciudad Vieja de Riga", "Castillo de Rundāle", "Parque Nacional de Gauja"],
    "Líbano": ["Baalbek", "Byblos", "Cuevas de Jeita"],
    "Liberia": ["Parque Nacional de Sapo", "Monrovia", "Cascadas de Kpatawee"],
    "Libia": ["Leptis Magna", "Sabratha", "Desierto de Libia"],
    "Liechtenstein": ["Castillo de Vaduz", "Museo Nacional de Liechtenstein", "Sendero del Príncipe"],
    "Lituania": ["Ciudad Vieja de Vilna", "Castillo de Trakai", "Dunas de Curonian Spit"],
    "Luxemburgo": ["Casamatas del Bock", "Puente Adolfo", "Ciudad Vieja de Luxemburgo"],
    "Macedonia del Norte": ["Lago Ohrid", "Monasterio de San Juan Bigorski", "Puente de Piedra"],
    "Madagascar": ["Parque Nacional de Tsingy de Bemaraha", "Avenida de los Baobabs", "Parque Nacional de Andasibe-Mantadia"],
    "Malasia": ["Torres Petronas", "Cuevas de Batu", "Parque Nacional de Taman Negara"],
    "Malaui": ["Lago Malaui", "Parque Nacional de Liwonde", "Monte Mulanje"],
    "Maldivas": ["Atolón de Malé", "Atolón de Ari", "Atolón de Baa"],
    "Malí": ["Tombuctú", "Djenné", "Parque Nacional de Boucle du Baoulé"],
    "Malta": ["La Valeta", "Mdina", "Templos Megalíticos de Malta"],
    "Marruecos": ["Mezquita de Hassan II", "Plaza de Jemaa el-Fnaa", "Medina de Fez"],
    "Mauricio": ["Isla de los Ciervos", "Siete Colores de la Tierra", "Parque Nacional de Black River Gorges"],
    "Mauritania": ["Parque Nacional de Banc d'Arguin", "Chinguetti", "Ouadane"],
    "México": ["Chichén Itzá", "Tulum", "Cancún"],
    "Micronesia": ["Islas Yap", "Islas Chuuk", "Islas Pohnpei"],
    "Moldavia": ["Monasterio de Curchi", "Fortaleza de Soroca", "Bodegas de Cricova"],
    "Mónaco": ["Casino de Montecarlo", "Palacio del Príncipe de Mónaco", "Jardín Exótico"],
    "Mongolia": ["Desierto de Gobi", "Parque Nacional de Gorkhi-Terelj", "Monasterio de Erdene Zuu"],
    "Montenegro": ["Bahía de Kotor", "Parque Nacional de Durmitor", "Ciudad Vieja de Budva"],
    "Mozambique": ["Isla de Mozambique", "Parque Nacional de Gorongosa", "Archipiélago de Bazaruto"],
    "Namibia": ["Desierto de Namib", "Parque Nacional de Etosha", "Cascadas de Epupa"],
    "Nauru": ["Laguna Buada", "Playa de Anibare", "Cueva de Moqua"],
    "Nepal": ["Monte Everest", "Templo de Pashupatinath", "Plaza Durbar de Katmandú"],
    "Nicaragua": ["Granada", "Volcán Masaya", "Isla de Ometepe"],
    "Níger": ["Parque Nacional de W", "Agadez", "Reserva Natural de Aïr y Ténéré"],
    "Nigeria": ["Parque Nacional de Yankari", "Lagos", "Abuja"],
    "Noruega": ["Fiordos de Noruega", "Aurora Boreal", "Geirangerfjord"],
    "Nueva Zelanda": ["Fiordland", "Montaña Cook", "Cuevas de Waitomo"],
    "Omán": ["Fuerte de Nizwa", "Wadi Shab", "Mezquita del Sultán Qaboos"],
    "Países Bajos": ["Canales de Ámsterdam", "Molinos de Kinderdijk", "Keukenhof"],
    "Pakistán": ["Fuerte de Lahore", "Mezquita de Badshahi", "Valle de Hunza"],
    "Palau": ["Laguna de las Medusas", "Roca de las Palomas", "Arrecife de Ngemelis"],
    "Panamá": ["Canal de Panamá", "Casco Antiguo", "Archipiélago de San Blas"],
    "Papúa Nueva Guinea": ["Río Sepik", "Montañas de Tari", "Parque Nacional de Varirata"],
    "Paraguay": ["Cataratas del Iguazú", "Ruinas de Jesús de Tavarangue", "Pantanal"],
    "Perú": ["Machu Picchu", "Lago Titicaca", "Líneas de Nazca"],
    "Polonia": ["Ciudad Vieja de Cracovia", "Mina de sal de Wieliczka", "Castillo de Malbork"],
    "Portugal": ["Torre de Belém", "Monasterio de los Jerónimos", "Palacio de la Pena"],
    "Reino Unido": ["Big Ben", "Stonehenge", "Castillo de Edimburgo"],
    "República Centroafricana": ["Parque Nacional de Dzanga-Sangha", "Cascadas de Boali", "Reserva de Manovo-Gounda St. Floris"],
    "República Checa": ["Castillo de Praga", "Puente de Carlos", "Ciudad Vieja de Praga"],
    "República Democrática del Congo": ["Parque Nacional de Virunga", "Parque Nacional de Kahuzi-Biega", "Parque Nacional de Salonga"],
    "República Dominicana": ["Playa de Bávaro", "Santo Domingo", "Playa de Punta Cana"],
    "Ruanda": ["Parque Nacional de los Volcanes", "Parque Nacional de Akagera", "Parque Nacional de Nyungwe"],
    "Rumania": ["Castillo de Bran", "Castillo de Peleș", "Ciudadela de Sighișoara"],
    "Rusia": ["Plaza Roja", "Museo del Hermitage", "Lago Baikal"],
    "Samoa": ["To Sua Ocean Trench", "Cascadas de Papaseea", "Playa de Lalomanu"],
    "San Cristóbal y Nieves": ["Fortaleza de Brimstone Hill", "Playa de Pinney's", "Parque Nacional de Central Forest Reserve"],
    "San Marino": ["Monte Titano", "Basílica de San Marino", "Museo de Estado"],
    "San Vicente y las Granadinas": ["La Soufrière", "Playa de Dark View Falls", "Jardines Botánicos de San Vicente"],
    "Santa Lucía": ["Los Pitones", "Playa de Reduit", "Cascadas de Diamond"],
    "Santo Tomé y Príncipe": ["Parque Nacional de Ôbo", "Isla de Rolas", "Playa de Pico Cão Grande"],
    "Senegal": ["Isla de Gorée", "Parque Nacional de Niokolo-Koba", "Lago Rosa"],
    "Serbia": ["Fortaleza de Belgrado", "Monasterio de Studenica", "Parque Nacional de Tara"],
    "Seychelles": ["Playa de Anse Source d'Argent", "Valle de Mai", "Playa de Anse Lazio"],
    "Sierra Leona": ["Playa de River Number Two", "Islas de Tiwai", "Parque Nacional de Outamba-Kilimi"],
    "Singapur": ["Gardens by the Bay", "Marina Bay Sands", "Sentosa"],
    "Siria": ["Ciudad Vieja de Damasco", "Palmira", "Crac de los Caballeros"],
    "Somalia": ["Parque Nacional de Laas Geel", "Mogadiscio", "Hargeisa"],
    "Sri Lanka": ["Sigiriya", "Templo del Diente de Buda", "Parque Nacional de Yala"],
    "Suazilandia": ["Parque Nacional de Hlane", "Reserva de Caza de Mlilwane", "Cascadas de Malolotja"],
    "Sudáfrica": ["Parque Nacional Kruger", "Mesa de la Montaña", "Cabo de Buena Esperanza"],
    "Sudán": ["Pirámides de Meroe", "Jebel Barkal", "Parque Nacional de Dinder"],
    "Sudán del Sur": ["Parque Nacional de Boma", "Parque Nacional de Bandingilo", "Parque Nacional de Southern"],
    "Suecia": ["Gamla Stan", "Museo Vasa", "Aurora Boreal"],
    "Suiza": ["Matterhorn", "Jungfrau", "Lago de Ginebra"],
    "Surinam": ["Parque Nacional de Brownsberg", "Reserva Natural de Central Suriname", "Fuerte Zeelandia"],
    "Tailandia": ["Gran Palacio de Bangkok", "Templo de Wat Arun", "Playa de Phi Phi"],
    "Tanzania": ["Parque Nacional del Serengeti", "Monte Kilimanjaro", "Parque Nacional de Ngorongoro"],
    "Tayikistán": ["Parque Nacional de las Montañas Pamir", "Lago Karakul", "Fuerte de Hulbuk"],
    "Timor Oriental": ["Cristo Rei de Dili", "Parque Nacional de Nino Konis Santana", "Cueva de Balibo"],
    "Togo": ["Parque Nacional de Fazao-Malfakassa", "Lomé", "Cascadas de Kpalimé"],
    "Tonga": ["Arrecife de Humpback Whales", "Cuevas de Anahulu", "Playa de Ha'atafu"],
    "Trinidad y Tobago": ["Playa de Maracas", "Cascadas de Argyle", "Fuerte King George"],
    "Túnez": ["Ruinas de Cartago", "Mezquita de Uqba", "Anfiteatro de El Djem"],
    "Turkmenistán": ["Darvaza", "Ashgabat", "Merv"],
    "Turquía": ["Hagia Sophia", "Mezquita Azul", "Capadocia"],
    "Tuvalu": ["Atolón de Funafuti", "Isla de Nanumea", "Isla de Niulakita"],
    "Ucrania": ["Catedral de Santa Sofía", "Chernóbil", "Catedral de San Volodymyr"],
    "Uganda": ["Parque Nacional de la Reina Isabel", "Parque Nacional de Murchison Falls", "Parque Nacional de Bwindi Impenetrable"],
    "Uruguay": ["Colonia del Sacramento", "Punta del Este", "Montevideo"],
    "Uzbekistán": ["Samarcanda", "Bujará", "Jiva"],
    "Vanuatu": ["Cascadas de Mele", "Volcán Yasur", "Isla de Tanna"],
    "Vaticano": ["Basílica de San Pedro", "Capilla Sixtina", "Museos Vaticanos"],
    "Venezuela": ["Salto Ángel", "Parque Nacional de Canaima", "Archipiélago de Los Roques"],
    "Vietnam": ["Bahía de Ha Long", "Ciudad Imperial de Hué", "Ciudad Antigua de Hoi An"],
    "Yemen": ["Ciudad Vieja de Sana'a", "Shibam", "Socotra"],
    "Yibuti": ["Lago Assal", "Lago Abbe", "Parque Nacional de Day Forest"],
    "Zambia": ["Cataratas Victoria", "Parque Nacional de South Luangwa", "Parque Nacional de Kafue"],
    "Zimbabue": ["Cataratas Victoria", "Parque Nacional de Hwange", "Gran Zimbabue"]
}

paises_direcciones = {
    "Afganistán": ["Mezquita Azul de Mazar-i-Sharif, Mazar-i-Sharif", "Jardines de Babur, Kabul", "Fortaleza de Bala Hissar, Kabul"],
    "Albania": ["Castillo de Rozafa, Shkodër", "Plaza Skanderbeg, Tirana", "Anfiteatro de Durrës, Durrës"],
    "Alemania": ["Puerta de Brandeburgo, Pariser Platz, Berlín", "Catedral de Colonia, Domkloster 4, Colonia", "Castillo de Neuschwanstein, Neuschwansteinstraße 20, Schwangau"],
    "Andorra": ["Naturlandia, Carretera de la Rabassa, Sant Julià de Lòria", "Caldea, Parc de la Mola, 10, Escaldes-Engordany", "Vallnord, Carretera General 2, La Massana"],
    "Angola": ["Fortaleza de São Miguel, Luanda", "Parque Nacional de Kissama, Luanda", "Museo Nacional de Antropología, Luanda"],
    "Antigua y Barbuda": ["Nelson's Dockyard, English Harbour", "Shirley Heights, English Harbour", "Devil's Bridge, Indian Town"],
    "Arabia Saudita": ["Masjid al-Haram, La Meca", "Al-Masjid an-Nabawi, Medina", "Mada'in Saleh, Al-'Ula"],
    "Argelia": ["Casba de Argel, Argel", "Ruinas de Timgad, Batna", "M'Zab Valley, Ghardaïa"],
    "Argentina": ["Cataratas del Iguazú, Puerto Iguazú", "Glaciar Perito Moreno, Parque Nacional Los Glaciares", "Parque Nacional Los Glaciares, Santa Cruz"],
    "Armenia": ["Monasterio de Khor Virap, Lusarat", "Catedral de Echmiadzin, Vagharshapat", "Monasterio de Geghard, Goght"],
    "Australia": ["Ópera de Sídney, Bennelong Point, Sídney", "Gran Barrera de Coral, Queensland", "Uluru, Uluru-Kata Tjuta National Park, Northern Territory"],
    "Austria": ["Palacio de Schönbrunn, Schönbrunner Schloßstraße 47, Viena", "Catedral de San Esteban, Stephansplatz 3, Viena", "Palacio de Hofburg, Michaelerkuppel, Viena"],
    "Azerbaiyán": ["Ciudad Vieja de Bakú, Bakú", "Palacio de los Shirvanshahs, Bakú", "Torre de la Doncella, Bakú"],
    "Bahamas": ["Atlantis Paradise Island, Paradise Island", "Playa de Pink Sands, Harbour Island", "Parque Nacional Lucayan, Grand Bahama"],
    "Bangladés": ["Mezquita Baitul Mukarram, Daca", "Fuerte de Lalbagh, Daca", "Parque Nacional de Sundarbans, Khulna"],
    "Barbados": ["Playa de Crane, Saint Philip", "Cueva de Harrison, Saint Thomas", "Jardines de Andrómeda, Saint Joseph"],
    "Baréin": ["Fuerte de Baréin, Manama", "Mezquita Al-Fateh, Manama", "Museo Nacional de Baréin, Manama"],
    "Bélgica": ["Atomium, Square de l'Atomium, Bruselas", "Grand Place, Bruselas", "Manneken Pis, Bruselas"],
    "Belice": ["Gran Agujero Azul, Belice", "Ruinas de Xunantunich, Cayo", "Cayo Ambergris, San Pedro"],
    "Benín": ["Palacio Real de Abomey, Abomey", "Templo de los Pitones, Ouidah", "Parque Nacional de Pendjari, Pendjari"],
    "Bielorrusia": ["Castillo de Mir, Mir", "Castillo de Nesvizh, Nesvizh", "Parque Nacional de Belovezhskaya Pushcha, Brest"],
    "Birmania": ["Pagoda Shwedagon, Yangón", "Bagan, Mandalay", "Lago Inle, Shan State"],
    "Bolivia": ["Salar de Uyuni, Uyuni", "Lago Titicaca, Copacabana", "Parque Nacional Madidi, Rurrenabaque"],
    "Bosnia y Herzegovina": ["Puente Stari Most, Mostar", "Baščaršija, Sarajevo", "Fuerte de Blagaj, Blagaj"],
    "Botsuana": ["Delta del Okavango, Maun", "Parque Nacional Chobe, Kasane", "Reserva de Caza del Kalahari Central, Ghanzi"],
    "Brasil": ["Cristo Redentor, Río de Janeiro", "Cataratas del Iguazú, Foz do Iguaçu", "Playa de Copacabana, Río de Janeiro"],
    "Brunéi": ["Mezquita Omar Ali Saifuddien, Bandar Seri Begawan", "Palacio Nurul Iman, Bandar Seri Begawan", "Parque Nacional Ulu Temburong, Temburong"],
    "Bulgaria": ["Monasterio de Rila, Rila", "Catedral de Alejandro Nevski, Sofía", "Playa del Sol, Burgas"],
    "Burkina Faso": ["Parque Nacional de Arli, Arli", "Mezquita de Bobo-Dioulasso, Bobo-Dioulasso", "Ruinas de Loropéni, Loropéni"],
    "Burundi": ["Parque Nacional de Kibira, Muramvya", "Lago Tanganica, Bujumbura", "Cascadas de Kagera, Rutana"],
    "Bután": ["Monasterio de Taktsang, Paro", "Fuerte de Punakha, Punakha", "Monasterio de Tashichho Dzong, Thimphu"],
    "Cabo Verde": ["Playa de Santa María, Santa María", "Volcán Pico do Fogo, Fogo", "Valle de Paul, Santo Antão"],
    "Camboya": ["Angkor Wat, Siem Reap", "Angkor Thom, Siem Reap", "Tonlé Sap, Siem Reap"],
    "Camerún": ["Parque Nacional de Waza, Waza", "Montañas Mandara, Maroua", "Cascadas de Lobé, Kribi"],
    "Canadá": ["Cataratas del Niágara, Niagara Falls", "Parque Nacional Banff, Banff", "Torre CN, Toronto"],
    "Catar": ["Museo de Arte Islámico, Doha", "La Perla, Doha", "Souq Waqif, Doha"],
    "Chad": ["Lago Chad, N'Djamena", "Desierto de Ennedi, Fada", "Parque Nacional de Zakouma, Am Timan"],
    "Chile": ["Torres del Paine, Torres del Paine", "Desierto de Atacama, San Pedro de Atacama", "Isla de Pascua, Isla de Pascua"],
    "China": ["Gran Muralla China, Beijing", "Ciudad Prohibida, Beijing", "Ejército de Terracota, Xi'an"],
    "Chipre": ["Tumbas de los Reyes, Paphos", "Castillo de Kolossi, Limassol", "Monasterio de Kykkos, Troodos"],
    "Colombia": ["Ciudad Perdida, Sierra Nevada de Santa Marta", "Parque Nacional Natural Tayrona, Santa Marta", "Catedral de Sal de Zipaquirá, Zipaquirá"],
    "Comoras": ["Parque Nacional de Coelacanth, Moroni", "Monte Karthala, Moroni", "Playa de Itsandra, Moroni"],
    "Corea del Norte": ["Monte Paektu, Samjiyon", "Mausoleo de Kumsusan, Pyongyang", "Arco del Triunfo, Pyongyang"],
    "Corea del Sur": ["Palacio de Gyeongbokgung, Seúl", "Mercado de Namdaemun, Seúl", "Parque Nacional de Seoraksan, Sokcho"],
    "Costa de Marfil": ["Basílica de Nuestra Señora de la Paz, Yamoussoukro", "Parque Nacional de Taï, Taï", "Gran Mezquita de Kong, Kong"],
    "Costa Rica": ["Parque Nacional Manuel Antonio, Quepos", "Volcán Arenal, La Fortuna", "Parque Nacional Tortuguero, Tortuguero"],
    "Croacia": ["Murallas de Dubrovnik, Dubrovnik", "Parque Nacional de los Lagos de Plitvice, Plitvice Lakes", "Palacio de Diocleciano, Split"],
    "Cuba": ["El Malecón, La Habana", "Plaza de la Revolución, La Habana", "Varadero, Varadero"],
    "Dinamarca": ["La Sirenita, Copenhague", "Tivoli Gardens, Copenhague", "Castillo de Kronborg, Helsingør"],
    "Dominica": ["Boiling Lake, Morne Trois Pitons National Park", "Parque Nacional de Morne Trois Pitons, Morne Trois Pitons National Park", "Emerald Pool, Morne Trois Pitons National Park"],
    "Ecuador": ["Islas Galápagos, Galápagos", "Cotopaxi, Cotopaxi", "Quito, Quito"],
    "Egipto": ["Pirámides de Giza, Giza", "Templo de Karnak, Luxor", "Valle de los Reyes, Luxor"],
    "El Salvador": ["Parque Nacional El Boquerón, San Salvador", "Ruinas de Joya de Cerén, La Libertad", "Volcán de Izalco, Sonsonate"],
    "Emiratos Árabes Unidos": ["Burj Khalifa, Dubái", "Mezquita Sheikh Zayed, Abu Dhabi", "Palm Jumeirah, Dubái"],
    "Eritrea": ["Asmara, Asmara", "Massawa, Massawa", "Dahlak Archipelago, Dahlak"],
    "Eslovaquia": ["Castillo de Bratislava, Bratislava", "Castillo de Spiš, Spišské Podhradie", "Parque Nacional de Tatra, Tatra Mountains"],
    "Eslovenia": ["Lago Bled, Bled", "Cuevas de Postojna, Postojna", "Castillo de Predjama, Predjama"],
    "España": ["La Alhambra, Granada", "Sagrada Familia, Barcelona", "Museo del Prado, Madrid"],
    "Estados Unidos": ["Estado de la Libertad, Nueva York", "Gran Cañón, Arizona", "Parque Nacional de Yellowstone, Wyoming"],
    "Estonia": ["Ciudad Vieja de Tallin, Tallin", "Castillo de Toompea, Tallin", "Parque Nacional de Lahemaa, Lahemaa"],
    "Etiopía": ["Iglesias de Lalibela, Lalibela", "Parque Nacional de Simien, Simien Mountains", "Castillo de Fasil Ghebbi, Gondar"],
    "Filipinas": ["Isla de Boracay, Boracay", "Río Subterráneo de Puerto Princesa, Puerto Princesa", "Terrazas de Arroz de Banaue, Banaue"],
    "Finlandia": ["Aurora Boreal, Laponia", "Fortaleza de Suomenlinna, Helsinki", "Parque Nacional de Nuuksio, Espoo"],
    "Fiyi": ["Islas Mamanuca, Mamanuca Islands", "Islas Yasawa, Yasawa Islands", "Parque Nacional de Bouma, Taveuni"],
    "Francia": ["Torre Eiffel, París", "Palacio de Versalles, Versalles", "Mont Saint-Michel, Mont Saint-Michel"],
    "Gabón": ["Parque Nacional de Loango, Loango", "Parque Nacional de Lopé, Lopé", "Cascadas de Kongou, Kongou"],
    "Gambia": ["Parque Nacional de Kiang West, Kiang West", "Mercado de Albert, Banjul", "Fuerte James Island, Banjul"],
    "Georgia": ["Catedral de Svetitskhoveli, Mtskheta", "Monasterio de Gelati, Kutaisi", "Cuevas de Vardzia, Aspindza"],
    "Ghana": ["Fuerte de Elmina, Elmina", "Parque Nacional de Mole, Mole", "Mercado de Makola, Accra"],
    "Granada": ["Grand Anse Beach, St. George's", "Fort George, St. George's", "Playa de Morne Rouge, St. George's"],
    "Grecia": ["Acrópolis de Atenas, Atenas", "Santorini, Santorini", "Meteora, Kalambaka"],
    "Guatemala": ["Tikal, Petén", "Lago de Atitlán, Sololá", "Antigua Guatemala, Antigua Guatemala"],
    "Guinea": ["Cascadas de Kambadaga, Kindia", "Parque Nacional de Monte Nimba, Lola", "Islas de Los, Conakry"],
    "Guinea-Bisáu": ["Parque Nacional de Orango, Orango", "Islas Bijagós, Bijagós", "Fuerte de Cacheu, Cacheu"],
    "Guinea Ecuatorial": ["Isla de Bioko, Bioko", "Parque Nacional de Monte Alén, Monte Alén", "Cascadas de Iladyi, Iladyi"],
    "Guyana": ["Cascadas de Kaieteur, Kaieteur", "Parque Nacional de Iwokrama, Iwokrama", "Mercado de Stabroek, Georgetown"],
    "Haití": ["Citadelle Laferrière, Milot", "Palacio de Sans-Souci, Milot", "Playa de Labadee, Labadee"],
    "Honduras": ["Ruinas de Copán, Copán", "Parque Nacional de Pico Bonito, La Ceiba", "Islas de la Bahía, Roatán"],
    "Hungría": ["Parlamento de Budapest, Budapest", "Baños Széchenyi, Budapest", "Castillo de Buda, Budapest"],
    "India": ["Taj Mahal, Agra", "Fuerte Rojo, Delhi", "Templo Dorado, Amritsar"],
    "Indonesia": ["Borobudur, Magelang", "Bali, Bali", "Parque Nacional de Komodo, Komodo"],
    "Irak": ["Ciudadela de Erbil, Erbil", "Zigurat de Ur, Nasiriyah", "Mezquita de Al-Askari, Samarra"],
    "Irán": ["Persépolis, Shiraz", "Plaza de Naqsh-e Jahan, Isfahán", "Mezquita del Imán, Isfahán"],
    "Irlanda": ["Acantilados de Moher, Clare", "Castillo de Blarney, Cork", "Guinness Storehouse, Dublin"],
    "Islandia": ["Laguna Azul, Grindavík", "Geiser de Geysir, Haukadalur", "Cascadas de Gullfoss, Gullfoss"],
    "Islas Marshall": ["Atolón de Bikini, Bikini", "Isla de Majuro, Majuro", "Isla de Ebeye, Ebeye"],
    "Islas Salomón": ["Isla de Guadalcanal, Guadalcanal", "Isla de Malaita, Malaita", "Isla de Santa Isabel, Santa Isabel"],
    "Israel": ["Muro de los Lamentos, Jerusalén", "Mar Muerto, Mar Muerto", "Masada, Masada"],
    "Italia": ["Coliseo, Roma", "Canales de Venecia, Venecia", "Torre de Pisa, Pisa"],
    "Jamaica": ["Dunn's River Falls, Ocho Rios", "Blue Mountains, Blue Mountains", "Negril, Negril"],
    "Japón": ["Monte Fuji, Fuji", "Templo de Kinkaku-ji, Kyoto", "Santuario de Fushimi Inari, Kyoto"],
    "Jordania": ["Petra, Petra", "Mar Muerto, Mar Muerto", "Wadi Rum, Wadi Rum"],
    "Kazajistán": ["Lago Balkhash, Balkhash", "Parque Nacional de Altyn-Emel, Altyn-Emel", "Mausoleo de Khoja Ahmed Yasawi, Turkistan"],
    "Kenia": ["Parque Nacional de Masai Mara, Masai Mara", "Parque Nacional de Amboseli, Amboseli", "Parque Nacional de Tsavo, Tsavo"],
    "Kirguistán": ["Lago Issyk-Kul, Issyk-Kul", "Parque Nacional de Ala Archa, Ala Archa", "Tash Rabat, Naryn"],
    "Kiribati": ["Atolón de Tarawa, Tarawa", "Isla de Kiritimati, Kiritimati", "Isla de Tabuaeran, Tabuaeran"],
    "Kuwait": ["Torres de Kuwait, Kuwait City", "Gran Mezquita de Kuwait, Kuwait City", "Museo Nacional de Kuwait, Kuwait City"],
    "Laos": ["Luang Prabang, Luang Prabang", "Playa de las Jarras, Xiangkhouang", "Cascadas de Kuang Si, Luang Prabang"],
    "Lesoto": ["Parque Nacional de Sehlabathebe, Sehlabathebe", "Cascadas de Maletsunyane, Semonkong", "Paso de Sani, Sani"],
    "Letonia": ["Ciudad Vieja de Riga, Riga", "Castillo de Rundāle, Rundāle", "Parque Nacional de Gauja, Gauja"],
    "Líbano": ["Baalbek, Baalbek", "Byblos, Byblos", "Cuevas de Jeita, Jeita"],
    "Liberia": ["Parque Nacional de Sapo, Sapo", "Monrovia, Monrovia", "Cascadas de Kpatawee, Kpatawee"],
    "Libia": ["Leptis Magna, Khoms", "Sabratha, Sabratha", "Desierto de Libia, Libia"],
    "Liechtenstein": ["Castillo de Vaduz, Vaduz", "Museo Nacional de Liechtenstein, Vaduz", "Sendero del Príncipe, Vaduz"],
    "Lituania": ["Ciudad Vieja de Vilna, Vilna", "Castillo de Trakai, Trakai", "Dunas de Curonian Spit, Neringa"],
    "Luxemburgo": ["Casamatas del Bock, Luxembourg City", "Puente Adolfo, Luxembourg City", "Ciudad Vieja de Luxemburgo, Luxembourg City"],
    "Macedonia del Norte": ["Lago Ohrid, Ohrid", "Monasterio de San Juan Bigorski, Debar", "Puente de Piedra, Skopje"],
    "Madagascar": ["Parque Nacional de Tsingy de Bemaraha, Bemaraha", "Avenida de los Baobabs, Morondava", "Parque Nacional de Andasibe-Mantadia, Andasibe"],
    "Malasia": ["Torres Petronas, Kuala Lumpur", "Cuevas de Batu, Batu", "Parque Nacional de Taman Negara, Taman Negara"],
    "Malaui": ["Lago Malaui, Malawi", "Parque Nacional de Liwonde, Liwonde", "Monte Mulanje, Mulanje"],
    "Maldivas": ["Atolón de Malé, Malé", "Atolón de Ari, Ari", "Atolón de Baa, Baa"],
    "Malí": ["Tombuctú, Tombuctú", "Djenné, Djenné", "Parque Nacional de Boucle du Baoulé, Boucle du Baoulé"],
    "Malta": ["La Valeta, Valletta", "Mdina, Mdina", "Templos Megalíticos de Malta, Malta"],
    "Marruecos": ["Mezquita de Hassan II, Casablanca", "Plaza de Jemaa el-Fnaa, Marrakech", "Medina de Fez, Fez"],
    "Mauricio": ["Isla de los Ciervos, Mauricio", "Siete Colores de la Tierra, Chamarel", "Parque Nacional de Black River Gorges, Black River Gorges"],
    "Mauritania": ["Parque Nacional de Banc d'Arguin, Banc d'Arguin", "Chinguetti, Chinguetti", "Ouadane, Ouadane"],
    "México": ["Chichén Itzá, Yucatán", "Tulum, Quintana Roo", "Cancún, Quintana Roo"],
    "Micronesia": ["Islas Yap, Yap", "Islas Chuuk, Chuuk", "Islas Pohnpei, Pohnpei"],
    "Moldavia": ["Monasterio de Curchi, Curchi", "Fortaleza de Soroca, Soroca", "Bodegas de Cricova, Cricova"],
    "Mónaco": ["Casino de Montecarlo, Montecarlo", "Palacio del Príncipe de Mónaco, Montecarlo", "Jardín Exótico, Montecarlo"],
    "Mongolia": ["Desierto de Gobi, Gobi", "Parque Nacional de Gorkhi-Terelj, Terelj", "Monasterio de Erdene Zuu, Erdene Zuu"],
    "Montenegro": ["Bahía de Kotor, Kotor", "Parque Nacional de Durmitor, Durmitor", "Ciudad Vieja de Budva, Budva"],
    "Mozambique": ["Isla de Mozambique, Mozambique", "Parque Nacional de Gorongosa, Gorongosa", "Archipiélago de Bazaruto, Bazaruto"],
    "Namibia": ["Desierto de Namib, Namib", "Parque Nacional de Etosha, Etosha", "Cascadas de Epupa, Epupa"],
    "Nauru": ["Laguna Buada, Buada", "Playa de Anabar, Anabar", "Cueva de Moqua, Moqua"],
    "Nepal": ["Monte Everest, Everest", "Templo de Pashupatinath, Katmandú", "Plaza Durbar de Katmandú, Katmandú"],
    "Nicaragua": ["Granada, Granada", "Volcán Masaya, Masaya", "Isla de Ometepe, Ometepe"],
    "Níger": ["Parque Nacional de W, W", "Agadez, Agadez", "Reserva Natural de Aïr y Ténéré, Aïr y Ténéré"],
    "Nigeria": ["Parque Nacional de Yankari, Yankari", "Lagos, Lagos", "Abuja, Abuja"],
    "Noruega": ["Fiordos de Noruega, Noruega", "Aurora Boreal, Noruega", "Geirangerfjord, Geiranger"],
    "Nueva Zelanda": ["Fiordland, Fiordland", "Montaña Cook, Mount Cook", "Cuevas de Waitomo, Waitomo"],
    "Omán": ["Fuerte de Nizwa, Nizwa", "Wadi Shab, Wadi Shab", "Mezquita del Sultán Qaboos, Muscat"],
    "Países Bajos": ["Canales de Ámsterdam, Ámsterdam", "Molinos de Kinderdijk, Kinderdijk", "Keukenhof, Lisse"],
    "Pakistán": ["Fuerte de Lahore, Lahore", "Mezquita de Badshahi, Lahore", "Valle de Hunza, Hunza"],
    "Palau": ["Laguna de las Medusas, Palau", "Roca de las Palomas, Palau", "Arrecife de Ngemelis, Palau"],
    "Panamá": ["Canal de Panamá, Panamá", "Casco Antiguo, Panamá", "Archipiélago de San Blas, San Blas"],
    "Papúa Nueva Guinea": ["Río Sepik, Sepik", "Montañas de Tari, Tari", "Parque Nacional de Varirata, Varirata"],
    "Paraguay": ["Cataratas del Iguazú, Iguazú", "Ruinas de Jesús de Tavarangue, Jesús de Tavarangue", "Pantanal, Pantanal"],
    "Perú": ["Machu Picchu, Cusco", "Lago Titicaca, Puno", "Líneas de Nazca, Nazca"],
    "Polonia": ["Ciudad Vieja de Cracovia, Cracovia", "Mina de sal de Wieliczka, Wieliczka", "Castillo de Malbork, Malbork"],
    "Portugal": ["Torre de Belém, Lisboa", "Monasterio de los Jerónimos, Lisboa", "Palacio de la Pena, Sintra"],
    "Reino Unido": ["Big Ben, Londres", "Stonehenge, Wiltshire", "Castillo de Edimburgo, Edimburgo"],
    "República Centroafricana": ["Parque Nacional de Dzanga-Sangha, Dzanga-Sangha", "Cascadas de Boali, Boali", "Reserva de Manovo-Gounda St. Floris, Manovo-Gounda St. Floris"],
    "República Checa": ["Castillo de Praga, Praga", "Puente de Carlos, Praga", "Ciudad Vieja de Praga, Praga"],
    "República Democrática del Congo": ["Parque Nacional de Virunga, Virunga", "Parque Nacional de Kahuzi-Biega, Kahuzi-Biega", "Parque Nacional de Salonga, Salonga"],
    "República Dominicana": ["Playa de Bávaro, Bávaro", "Santo Domingo, Santo Domingo", "Playa de Punta Cana, Punta Cana"],
    "Ruanda": ["Parque Nacional de los Volcanes, Volcanes", "Parque Nacional de Akagera, Akagera", "Parque Nacional de Nyungwe, Nyungwe"],
    "Rumania": ["Castillo de Bran, Bran", "Castillo de Peleș, Sinaia", "Ciudadela de Sighișoara, Sighișoara"],
    "Rusia": ["Plaza Roja, Moscú", "Museo del Hermitage, San Petersburgo", "Lago Baikal, Baikal"],
    "Samoa": ["To Sua Ocean Trench, Samoa", "Cascadas de Papaseea, Samoa", "Playa de Lalomanu, Samoa"],
    "San Cristóbal y Nieves": ["Fortaleza de Brimstone Hill, Brimstone Hill", "Playa de Pinney's, Pinney's", "Parque Nacional de Central Forest Reserve, Central Forest Reserve"],
    "San Marino": ["Monte Titano, San Marino", "Basílica de San Marino, San Marino", "Museo de Estado, San Marino"],
    "San Vicente y las Granadinas": ["La Soufrière, La Soufrière", "Playa de Dark View Falls, Dark View Falls", "Jardines Botánicos de San Vicente, San Vicente"],
    "Santa Lucía": ["Los Pitones, Santa Lucía", "Playa de Reduit, Reduit", "Cascadas de Diamond, Diamond"],
    "Santo Tomé y Príncipe": ["Parque Nacional de Ôbo, Ôbo", "Isla de Rolas, Rolas", "Playa de Pico Cão Grande, Pico Cão Grande"],
    "Senegal": ["Isla de Gorée, Gorée", "Parque Nacional de Niokolo-Koba, Niokolo-Koba", "Lago Rosa, Dakar"],
    "Serbia": ["Fortaleza de Belgrado, Belgrado", "Monasterio de Studenica, Studenica", "Parque Nacional de Tara, Tara"],
    "Seychelles": ["Playa de Anse Source d'Argent, La Digue", "Valle de Mai, Praslin", "Playa de Anse Lazio, Praslin"],
    "Sierra Leona": ["Playa de River Number Two, River Number Two", "Islas de Tiwai, Tiwai", "Parque Nacional de Outamba-Kilimi, Outamba-Kilimi"],
    "Singapur": ["Gardens by the Bay, Singapur", "Marina Bay Sands, Singapur", "Sentosa, Singapur"],
    "Siria": ["Ciudad Vieja de Damasco, Damasco", "Palmira, Palmira", "Crac de los Caballeros, Crac de los Caballeros"],
    "Somalia": ["Parque Nacional de Laas Geel, Laas Geel", "Mogadiscio, Mogadiscio", "Hargeisa, Hargeisa"],
    "Sri Lanka": ["Sigiriya, Sigiriya", "Templo del Diente de Buda, Kandy", "Parque Nacional de Yala, Yala"],
    "Suazilandia": ["Parque Nacional de Hlane, Hlane", "Reserva de Caza de Mlilwane, Mlilwane", "Cascadas de Malolotja, Malolotja"],
    "Sudáfrica": ["Parque Nacional Kruger, Kruger", "Mesa de la Montaña, Ciudad del Cabo", "Cabo de Buena Esperanza, Ciudad del Cabo"],
    "Sudán": ["Pirámides de Meroe, Meroe", "Jebel Barkal, Jebel Barkal", "Parque Nacional de Dinder, Dinder"],
    "Sudán del Sur": ["Parque Nacional de Boma, Boma", "Parque Nacional de Bandingilo, Bandingilo", "Parque Nacional de Southern, Southern"],
    "Suecia": ["Gamla Stan, Estocolmo", "Museo Vasa, Estocolmo", "Aurora Boreal, Laponia"],
    "Suiza": ["Matterhorn, Zermatt", "Jungfrau, Jungfrau", "Lago de Ginebra, Ginebra"],
    "Surinam": ["Parque Nacional de Brownsberg, Brownsberg", "Reserva Natural de Central Suriname, Central Suriname", "Fuerte Zeelandia, Paramaribo"],
    "Tailandia": ["Gran Palacio de Bangkok, Bangkok", "Templo de Wat Arun, Bangkok", "Playa de Phi Phi, Phi Phi"],
    "Tanzania": ["Parque Nacional del Serengeti, Serengeti", "Monte Kilimanjaro, Kilimanjaro", "Parque Nacional de Ngorongoro, Ngorongoro"],
    "Tayikistán": ["Parque Nacional de las Montañas Pamir, Pamir", "Lago Karakul, Karakul", "Fuerte de Hulbuk, Hulbuk"],
    "Timor Oriental": ["Cristo Rei de Dili, Dili", "Parque Nacional de Nino Konis Santana, Nino Konis Santana", "Cueva de Balibo, Balibo"],
    "Togo": ["Parque Nacional de Fazao-Malfakassa, Fazao-Malfakassa", "Lomé, Lomé", "Cascadas de Kpalimé, Kpalimé"],
    "Tonga": ["Arrecife de Humpback Whales, Tonga", "Cuevas de Anahulu, Anahulu", "Playa de Ha'atafu, Ha'atafu"],
    "Trinidad y Tobago": ["Playa de Maracas, Maracas", "Cascadas de Argyle, Argyle", "Fuerte King George, Scarborough"],
    "Túnez": ["Ruinas de Cartago, Cartago", "Mezquita de Uqba, Kairouan", "Anfiteatro de El Djem, El Djem"],
    "Turkmenistán": ["Darvaza, Darvaza", "Ashgabat, Ashgabat", "Merv, Merv"],
    "Turquía": ["Hagia Sophia, Estambul", "Mezquita Azul, Estambul", "Capadocia, Capadocia"],
    "Tuvalu": ["Atolón de Funafuti, Funafuti", "Isla de Nanumea, Nanumea", "Isla de Niulakita, Niulakita"],
    "Ucrania": ["Catedral de Santa Sofía, Kiev", "Chernóbil, Chernóbil", "Catedral de San Volodymyr, Kiev"],
    "Uganda": ["Parque Nacional de la Reina Isabel, Queen Elizabeth National Park", "Parque Nacional de Murchison Falls, Murchison Falls", "Parque Nacional de Bwindi Impenetrable, Bwindi Impenetrable"],
    "Uruguay": ["Colonia del Sacramento, Colonia del Sacramento", "Punta del Este, Punta del Este", "Montevideo, Montevideo"],
    "Uzbekistán": ["Samarcanda, Samarcanda", "Bujará, Bujará", "Jiva, Jiva"],
    "Vanuatu": ["Cascadas de Mele, Mele", "Volcán Yasur, Yasur", "Isla de Tanna, Tanna"],
    "Vaticano": ["Basílica de San Pedro, Ciudad del Vaticano", "Capilla Sixtina, Ciudad del Vaticano", "Museos Vaticanos, Ciudad del Vaticano"],
    "Venezuela": ["Salto Ángel, Canaima", "Parque Nacional de Canaima, Canaima", "Archipiélago de Los Roques, Los Roques"],
    "Vietnam": ["Bahía de Ha Long, Ha Long", "Ciudad Imperial de Hué, Hué", "Ciudad Antigua de Hoi An, Hoi An"],
    "Yemen": ["Ciudad Vieja de Sana'a, Sana'a", "Shibam, Shibam", "Socotra, Socotra"],
    "Yibuti": ["Lago Assal, Assal", "Lago Abbe, Abbe", "Parque Nacional de Day Forest, Day Forest"],
    "Zambia": ["Cataratas Victoria, Livingstone", "Parque Nacional de South Luangwa, South Luangwa", "Parque Nacional de Kafue, Kafue"],
    "Zimbabue": ["Cataratas Victoria, Victoria Falls", "Parque Nacional de Hwange, Hwange", "Gran Zimbabue, Masvingo"]
}

